import React, { useState } from 'react';
import { RecipeResponse } from '../types';
import {
  Clock,
  Flame,
  Users,
  ChefHat,
  Copy,
  Check,
  RotateCcw,
  Sparkles,
  Lightbulb,
  CheckCircle2,
  Printer,
  UtensilsCrossed,
  Heart,
  Download,
  X,
  FileText,
  FileCode
} from 'lucide-react';

interface RecipeCardProps {
  recipe: RecipeResponse;
  onClear?: () => void;
  onCloseModal?: () => void;
  isFavorite?: boolean;
  onToggleFavorite?: () => void;
}

export const RecipeCard: React.FC<RecipeCardProps> = ({
  recipe,
  onClear,
  onCloseModal,
  isFavorite: externalIsFavorite,
  onToggleFavorite,
}) => {
  const [copied, setCopied] = useState(false);
  const [internalFavorite, setInternalFavorite] = useState(false);
  const [downloadMenuOpen, setDownloadMenuOpen] = useState(false);
  const [completedSteps, setCompletedSteps] = useState<number[]>([]);
  const [checkedIngredients, setCheckedIngredients] = useState<number[]>([]);

  const isFav = externalIsFavorite !== undefined ? externalIsFavorite : internalFavorite;

  const handleFavoriteClick = () => {
    if (onToggleFavorite) {
      onToggleFavorite();
    } else {
      setInternalFavorite(!internalFavorite);
    }
  };

  const toggleStep = (index: number) => {
    setCompletedSteps((prev) =>
      prev.includes(index) ? prev.filter((i) => i !== index) : [...prev, index]
    );
  };

  const toggleIngredient = (index: number) => {
    setCheckedIngredients((prev) =>
      prev.includes(index) ? prev.filter((i) => i !== index) : [...prev, index]
    );
  };

  const formatRecipeText = () => {
    return `
==================================================
🍽️ ${recipe.recipeName.toUpperCase()}
==================================================
Cuisine: ${recipe.cuisine} | Difficulty: ${recipe.difficulty}
Servings: ${recipe.servings} | Calories: ${recipe.estimatedCalories}
Prep Time: ${recipe.prepTime} | Cook Time: ${recipe.cookTime}

INGREDIENTS:
${recipe.ingredients.map((ing) => `• ${typeof ing === 'string' ? ing : `${ing.item} (${ing.amount || ''})`}`).join('\n')}

${recipe.missingIngredients && recipe.missingIngredients.length > 0 ? `MISSING BASICS / ESSENTIALS:\n${recipe.missingIngredients.map((m) => `+ ${m}`).join('\n')}\n\n` : ''}INSTRUCTIONS:
${recipe.instructions.map((step, idx) => `${idx + 1}. ${step}`).join('\n')}

CHEF TIPS:
${recipe.cookingTips.map((tip) => `• ${tip}`).join('\n')}

NUTRITION PER SERVING:
Protein: ${recipe.nutrition.protein} | Carbs: ${recipe.nutrition.carbs} | Fat: ${recipe.nutrition.fat} | Fiber: ${recipe.nutrition.fiber}
==================================================
Generated by AI Recipe Generator - Cook Smart, Reduce Waste
`.trim();
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(formatRecipeText());
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch (err) {
      console.error('Failed to copy text', err);
    }
  };

  const handleDownloadTxt = () => {
    const text = formatRecipeText();
    const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${recipe.recipeName.toLowerCase().replace(/[^a-z0-9]+/g, '_')}_recipe.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    setDownloadMenuOpen(false);
  };

  const handleDownloadJson = () => {
    const jsonStr = JSON.stringify(recipe, null, 2);
    const blob = new Blob([jsonStr], { type: 'application/json;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${recipe.recipeName.toLowerCase().replace(/[^a-z0-9]+/g, '_')}_recipe.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    setDownloadMenuOpen(false);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div
      id="recipe-card-container"
      className="printable-recipe bg-white dark:bg-slate-900 rounded-3xl border border-orange-100 dark:border-slate-800 shadow-xl shadow-orange-500/5 overflow-hidden transition-all my-6 relative"
    >
      {/* Modal Close Button if opened in a dialog */}
      {onCloseModal && (
        <button
          id="close-recipe-modal-btn"
          onClick={onCloseModal}
          className="no-print absolute top-4 right-4 z-20 p-2 rounded-full bg-slate-900/60 hover:bg-slate-900 text-white backdrop-blur-md transition-colors cursor-pointer"
          aria-label="Close modal"
        >
          <X className="w-5 h-5" />
        </button>
      )}

      {/* Recipe Header Banner */}
      <div className="bg-gradient-to-r from-orange-600 via-amber-500 to-orange-500 p-6 sm:p-8 text-white relative overflow-hidden">
        <div className="absolute -right-8 -bottom-8 opacity-10 pointer-events-none no-print">
          <UtensilsCrossed className="w-64 h-64 text-white" />
        </div>

        <div className="relative z-10 flex flex-col md:flex-row md:items-start justify-between gap-6">
          <div className="space-y-3 max-w-2xl">
            <div className="flex flex-wrap items-center gap-2">
              <span className="px-3 py-1 bg-white/20 backdrop-blur-md text-white text-xs font-bold rounded-full border border-white/30 uppercase tracking-wider">
                {recipe.cuisine} Cuisine
              </span>
              {recipe.dietaryTag && (
                <span className="px-3 py-1 bg-emerald-950/30 backdrop-blur-md text-emerald-100 text-xs font-bold rounded-full border border-emerald-300/30 uppercase tracking-wider">
                  {recipe.dietaryTag}
                </span>
              )}
              <span className="px-3 py-1 bg-amber-950/30 backdrop-blur-md text-amber-100 text-xs font-bold rounded-full border border-amber-300/30">
                {recipe.difficulty} Difficulty
              </span>
            </div>

            <h2 className="text-2xl sm:text-3xl lg:text-4xl font-extrabold text-white tracking-tight leading-tight">
              {recipe.recipeName}
            </h2>

            {recipe.summary && (
              <p className="text-orange-50 text-sm sm:text-base leading-relaxed font-normal opacity-95">
                {recipe.summary}
              </p>
            )}
          </div>

          {/* Header Action Buttons */}
          <div className="no-print flex items-center gap-2 self-start flex-wrap relative">
            <button
              id="save-recipe-btn"
              onClick={handleFavoriteClick}
              className={`p-2.5 rounded-xl text-sm font-semibold flex items-center gap-2 transition-all cursor-pointer ${
                isFav
                  ? 'bg-rose-500 text-white shadow-md'
                  : 'bg-white/20 hover:bg-white/30 text-white backdrop-blur-md'
              }`}
              title={isFav ? 'Remove from favorites' : 'Save to favorites'}
            >
              <Heart className={`w-4 h-4 ${isFav ? 'fill-white' : ''}`} />
              <span className="hidden sm:inline">{isFav ? 'Saved' : 'Favorite'}</span>
            </button>

            {/* Download Dropdown Toggle */}
            <div className="relative">
              <button
                id="download-recipe-dropdown-btn"
                onClick={() => setDownloadMenuOpen(!downloadMenuOpen)}
                className="p-2.5 bg-white/20 hover:bg-white/30 text-white rounded-xl text-sm font-semibold backdrop-blur-md transition-all flex items-center gap-2 cursor-pointer"
                title="Download Recipe"
              >
                <Download className="w-4 h-4" />
                <span className="hidden sm:inline">Download</span>
              </button>

              {downloadMenuOpen && (
                <div className="absolute right-0 mt-2 w-48 bg-white dark:bg-slate-800 rounded-2xl shadow-xl border border-slate-200 dark:border-slate-700 py-1.5 z-30 animate-in fade-in zoom-in-95">
                  <button
                    onClick={handleDownloadTxt}
                    className="w-full flex items-center gap-2.5 px-4 py-2 text-xs font-semibold text-slate-700 dark:text-slate-200 hover:bg-orange-50 dark:hover:bg-slate-700 cursor-pointer"
                  >
                    <FileText className="w-4 h-4 text-orange-600" />
                    Text File (.txt)
                  </button>
                  <button
                    onClick={handleDownloadJson}
                    className="w-full flex items-center gap-2.5 px-4 py-2 text-xs font-semibold text-slate-700 dark:text-slate-200 hover:bg-orange-50 dark:hover:bg-slate-700 cursor-pointer"
                  >
                    <FileCode className="w-4 h-4 text-amber-500" />
                    JSON File (.json)
                  </button>
                </div>
              )}
            </div>

            <button
              id="print-recipe-btn"
              onClick={handlePrint}
              className="p-2.5 bg-white/20 hover:bg-white/30 text-white rounded-xl text-sm font-semibold backdrop-blur-md transition-all flex items-center gap-2 cursor-pointer"
              title="Print Recipe"
            >
              <Printer className="w-4 h-4" />
              <span className="hidden sm:inline">Print</span>
            </button>
          </div>
        </div>

        {/* Quick Recipe Info Cards */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mt-6 pt-6 border-t border-white/20">
          <div className="bg-white/10 backdrop-blur-md p-3 rounded-2xl border border-white/15 flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-white/20 flex items-center justify-center shrink-0">
              <Clock className="w-5 h-5 text-white" />
            </div>
            <div>
              <p className="text-[11px] text-orange-100 uppercase tracking-wider font-medium">Prep Time</p>
              <p className="text-sm font-bold text-white">{recipe.prepTime}</p>
            </div>
          </div>

          <div className="bg-white/10 backdrop-blur-md p-3 rounded-2xl border border-white/15 flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-white/20 flex items-center justify-center shrink-0">
              <Flame className="w-5 h-5 text-white" />
            </div>
            <div>
              <p className="text-[11px] text-orange-100 uppercase tracking-wider font-medium">Cook Time</p>
              <p className="text-sm font-bold text-white">{recipe.cookTime}</p>
            </div>
          </div>

          <div className="bg-white/10 backdrop-blur-md p-3 rounded-2xl border border-white/15 flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-white/20 flex items-center justify-center shrink-0">
              <Users className="w-5 h-5 text-white" />
            </div>
            <div>
              <p className="text-[11px] text-orange-100 uppercase tracking-wider font-medium">Servings</p>
              <p className="text-sm font-bold text-white">{recipe.servings} Person{recipe.servings > 1 ? 's' : ''}</p>
            </div>
          </div>

          <div className="bg-white/10 backdrop-blur-md p-3 rounded-2xl border border-white/15 flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-white/20 flex items-center justify-center shrink-0">
              <ChefHat className="w-5 h-5 text-white" />
            </div>
            <div>
              <p className="text-[11px] text-orange-100 uppercase tracking-wider font-medium">Calories</p>
              <p className="text-sm font-bold text-white">{recipe.estimatedCalories}</p>
            </div>
          </div>
        </div>
      </div>

      {/* Main Body */}
      <div className="p-6 sm:p-8 space-y-8">
        
        {/* Ingredients & Nutrition Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          
          {/* Ingredients Column */}
          <div className="lg:col-span-2 space-y-4">
            <div className="flex items-center justify-between">
              <h3 className="text-lg font-bold text-slate-900 dark:text-white flex items-center gap-2">
                <UtensilsCrossed className="w-5 h-5 text-orange-600 dark:text-orange-500" />
                Required Ingredients ({recipe.ingredients.length})
              </h3>
              <span className="text-xs text-slate-500 dark:text-slate-400 font-medium no-print">
                Tap items to mark as ready
              </span>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
              {recipe.ingredients.map((ing, idx) => {
                const ingText = typeof ing === 'string' ? ing : `${ing.item} ${ing.amount ? `(${ing.amount})` : ''}`;
                const isChecked = checkedIngredients.includes(idx);
                return (
                  <button
                    key={idx}
                    id={`ingredient-item-${idx}`}
                    onClick={() => toggleIngredient(idx)}
                    className={`p-3 rounded-xl border text-left text-sm flex items-start gap-3 transition-all cursor-pointer ${
                      isChecked
                        ? 'bg-emerald-50/60 dark:bg-emerald-950/30 border-emerald-200 dark:border-emerald-900 text-slate-400 dark:text-slate-500 line-through'
                        : 'bg-slate-50 dark:bg-slate-800/80 border-slate-200/80 dark:border-slate-700 text-slate-800 dark:text-slate-200 hover:border-orange-200 dark:hover:border-orange-800 hover:bg-orange-50/30 dark:hover:bg-slate-800'
                    }`}
                  >
                    <div className={`w-5 h-5 rounded-md flex items-center justify-center shrink-0 mt-0.5 border transition-colors ${
                      isChecked
                        ? 'bg-emerald-600 border-emerald-600 text-white'
                        : 'border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-900'
                    }`}>
                      {isChecked && <Check className="w-3.5 h-3.5 stroke-[3]" />}
                    </div>
                    <span className="font-medium leading-snug">{ingText}</span>
                  </button>
                );
              })}
            </div>

            {/* Missing Essential Ingredients Section */}
            {recipe.missingIngredients && recipe.missingIngredients.length > 0 && (
              <div className="mt-4 p-4 bg-amber-50/70 dark:bg-amber-950/40 border border-amber-200/90 dark:border-amber-900/60 rounded-2xl space-y-2">
                <div className="flex items-center gap-2 text-amber-900 dark:text-amber-300 font-bold text-sm">
                  <span className="w-2 h-2 rounded-full bg-amber-500 animate-pulse"></span>
                  <span>Missing Essential Ingredients (Pantry / Basics)</span>
                </div>
                <div className="flex flex-wrap gap-1.5">
                  {recipe.missingIngredients.map((item, idx) => (
                    <span
                      key={idx}
                      className="px-2.5 py-1 bg-amber-100 dark:bg-amber-900/60 text-amber-900 dark:text-amber-200 rounded-lg text-xs font-semibold border border-amber-200 dark:border-amber-800"
                    >
                      + {item}
                    </span>
                  ))}
                </div>
              </div>
            )}
          </div>

          {/* Nutrition Info Column */}
          <div className="bg-orange-50/60 dark:bg-slate-800/60 rounded-2xl p-5 border border-orange-100/80 dark:border-slate-700 space-y-4 h-fit">
            <h3 className="text-base font-bold text-slate-900 dark:text-white flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-orange-600 dark:text-orange-400" />
              Nutrition per Serving
            </h3>

            <div className="grid grid-cols-2 gap-3 text-center">
              <div className="bg-white dark:bg-slate-900 p-3 rounded-xl border border-orange-100 dark:border-slate-800 shadow-xs">
                <p className="text-[11px] font-bold uppercase tracking-wider text-slate-400">Protein</p>
                <p className="text-base font-extrabold text-orange-600 dark:text-orange-400 mt-0.5">{recipe.nutrition.protein}</p>
              </div>

              <div className="bg-white dark:bg-slate-900 p-3 rounded-xl border border-orange-100 dark:border-slate-800 shadow-xs">
                <p className="text-[11px] font-bold uppercase tracking-wider text-slate-400">Carbs</p>
                <p className="text-base font-extrabold text-amber-600 dark:text-amber-400 mt-0.5">{recipe.nutrition.carbs}</p>
              </div>

              <div className="bg-white dark:bg-slate-900 p-3 rounded-xl border border-orange-100 dark:border-slate-800 shadow-xs">
                <p className="text-[11px] font-bold uppercase tracking-wider text-slate-400">Fat</p>
                <p className="text-base font-extrabold text-rose-500 dark:text-rose-400 mt-0.5">{recipe.nutrition.fat}</p>
              </div>

              <div className="bg-white dark:bg-slate-900 p-3 rounded-xl border border-orange-100 dark:border-slate-800 shadow-xs">
                <p className="text-[11px] font-bold uppercase tracking-wider text-slate-400">Fiber</p>
                <p className="text-base font-extrabold text-emerald-600 dark:text-emerald-400 mt-0.5">{recipe.nutrition.fiber}</p>
              </div>
            </div>

            <p className="text-[11px] text-slate-500 dark:text-slate-400 text-center leading-tight">
              * Estimated values calculated by AI based on standard ingredient portion sizes.
            </p>
          </div>
        </div>

        {/* Step-by-Step Instructions */}
        <div className="space-y-4 pt-4 border-t border-slate-100 dark:border-slate-800">
          <div className="flex items-center justify-between">
            <h3 className="text-xl font-extrabold text-slate-900 dark:text-white flex items-center gap-2">
              <ChefHat className="w-6 h-6 text-orange-600 dark:text-orange-500" />
              Step-by-Step Instructions
            </h3>
            <span className="text-xs font-semibold text-orange-600 dark:text-orange-400 bg-orange-100/60 dark:bg-orange-950/60 px-2.5 py-1 rounded-full no-print">
              {completedSteps.length} / {recipe.instructions.length} Steps Completed
            </span>
          </div>

          <div className="space-y-3">
            {recipe.instructions.map((step, idx) => {
              const isDone = completedSteps.includes(idx);
              return (
                <div
                  key={idx}
                  id={`instruction-step-${idx}`}
                  onClick={() => toggleStep(idx)}
                  className={`p-4 sm:p-5 rounded-2xl border transition-all cursor-pointer flex gap-4 ${
                    isDone
                      ? 'bg-slate-50 dark:bg-slate-800/40 border-slate-200 dark:border-slate-800 opacity-60'
                      : 'bg-white dark:bg-slate-800/80 border-slate-200/80 dark:border-slate-700 hover:border-orange-300 dark:hover:border-orange-700 hover:shadow-md'
                  }`}
                >
                  <div
                    className={`w-8 h-8 rounded-full flex items-center justify-center shrink-0 font-bold text-sm transition-colors ${
                      isDone
                        ? 'bg-emerald-600 text-white'
                        : 'bg-orange-100 dark:bg-orange-950/80 text-orange-700 dark:text-orange-300'
                    }`}
                  >
                    {isDone ? <Check className="w-4 h-4 stroke-[3]" /> : idx + 1}
                  </div>

                  <div className="space-y-1">
                    <p className={`text-sm sm:text-base leading-relaxed ${
                      isDone ? 'line-through text-slate-400 dark:text-slate-500' : 'text-slate-800 dark:text-slate-200 font-medium'
                    }`}>
                      {step}
                    </p>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Cooking Tips Section */}
        {recipe.cookingTips && recipe.cookingTips.length > 0 && (
          <div className="bg-amber-50/80 dark:bg-amber-950/30 border border-amber-200/80 dark:border-amber-900/50 rounded-2xl p-5 space-y-3">
            <h4 className="text-base font-bold text-amber-900 dark:text-amber-300 flex items-center gap-2">
              <Lightbulb className="w-5 h-5 text-amber-600 dark:text-amber-400 fill-amber-500/20" />
              Chef's Pro Tips
            </h4>
            <ul className="space-y-2">
              {recipe.cookingTips.map((tip, idx) => (
                <li key={idx} className="flex items-start gap-2.5 text-sm text-amber-950 dark:text-amber-200 font-medium">
                  <span className="text-amber-500 font-bold text-base">•</span>
                  <span>{tip}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Bottom Action Toolbar */}
        <div className="no-print pt-6 border-t border-slate-100 dark:border-slate-800 flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-3 w-full sm:w-auto">
            <button
              id="copy-recipe-btn"
              onClick={handleCopy}
              className={`flex-1 sm:flex-initial flex items-center justify-center gap-2 px-5 py-3 rounded-xl font-bold text-sm transition-all shadow-md cursor-pointer ${
                copied
                  ? 'bg-emerald-600 text-white shadow-emerald-600/20'
                  : 'bg-orange-600 hover:bg-orange-700 text-white shadow-orange-600/20'
              }`}
            >
              {copied ? (
                <>
                  <CheckCircle2 className="w-4 h-4" />
                  Recipe Copied!
                </>
              ) : (
                <>
                  <Copy className="w-4 h-4" />
                  Copy Recipe
                </>
              )}
            </button>

            {onClear && (
              <button
                id="clear-recipe-btn"
                onClick={onClear}
                className="flex-1 sm:flex-initial flex items-center justify-center gap-2 px-5 py-3 bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-200 font-semibold text-sm rounded-xl transition-all cursor-pointer"
              >
                <RotateCcw className="w-4 h-4" />
                Clear & Start Over
              </button>
            )}
          </div>

          <p className="text-xs text-slate-400 font-medium text-center sm:text-right">
            Bon Appétit! Enjoy your meal 🍽️
          </p>
        </div>

      </div>
    </div>
  );
};
